[project]
name = "ev-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "daft>=0.6.13",
    "dotenv>=0.9.9",
    "ev-sdk>=0.1.3",
    "langchain-text-splitters>=1.0.0",
]
